### ISSUE TITLE
CSS预处理器支持

### ISSUE THREAD

**Issue by rivers-fighting** [tnfe/concent-pro#4]
是不是可以考虑加入 像Sass、Less和Stylus这类的CSS预处理器，更推荐用哪一个？

**Comment by fantasticsoul** [comment]
cra默认支持sass的，可以见 configs/webpack.config.js

**Comment by fantasticsoul** [comment]
已支持sass，配合webpack4，需要 `npm i node-sass@4` `npm i sass-loader@10`
